pollme/urls.py
from django.contrib import admin 
from django.urls import path, include , re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import serve


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('polls/', include('polls.urls', namespace="polls")),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    
   
    
    

    
    
   
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path , include , re_path
from . import views
from django.contrib import admin 
from django.urls import path, include , re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "polls"

urlpatterns = [
    path('list/', views.polls_list, name='list'),
    path('list/user/', views.list_by_user, name='list_by_user'),
    path('add/', views.polls_add, name='add'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.endpoll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/',
         views.choice_delete, name='choice_delete'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
    path('<int:poll_id>/comment/', views.comments, name='comments'),
    path('comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    

 
   

  
   
    
]

urlpatterns += staticfiles_urlpatterns()

polls/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
import secrets
from django.urls import reverse
from django import forms
from django.conf import settings
from django.db import migrations
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Count


class Poll(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)
    image = models.ImageField(upload_to='poll_images', blank=True, null=True)
    video = models.FileField(upload_to='poll_videos', blank=True, null=True)
    
    def user_can_vote(self, user):
        """ 
        Return False if user already voted
        """
        user_votes = user.vote_set.all()
        qs = user_votes.filter(poll=self)
        if qs.exists():
            return False
        return True

    @property
    def get_vote_count(self):
        return self.vote_set.count()

    def get_result_dict(self):
        res = []
        for choice in self.choice_set.all():
            d = {}
            d['text'] = choice.choice_text
            d['num_votes'] = choice.get_vote_count()
          

            if not self.get_vote_count:
                d['percentage'] = 0
            else:
                d['percentage'] = (choice.get_vote_count() / self.get_vote_count)*100


           
            
            res.append(d)
        return res
   

    def __str__(self):
        return self.text
 
  
class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    

    def __str__(self):
        return self.choice_text

    def get_vote_count(self):
     return self.vote_set.count()
    
    


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    

    def __str__(self):
        return f'{self.poll.text[:15]} - {self.choice.choice_text[:15]} - {self.user.username}'
    
    
    def classify_poll_results(poll_id):
        # Get all votes for the given poll, and annotate each choice with the number of votes
        votes = Vote.objects.filter(poll_id=poll_id).select_related('user', 'choice')
        choices = Choice.objects.filter(poll_id=poll_id).annotate(num_votes=Count('vote')).order_by('-num_votes')

        # Get the choices with the most votes (winners) and the rest (losers)
        max_votes = choices.first().num_votes
        winners = [choice for choice in choices if choice.num_votes == max_votes]
        losers = [choice for choice in choices if choice not in winners]

        # Get the users who voted for each choice
        winner_users = [vote.user.username for vote in votes if vote.choice in winners]
        loser_users = [vote.user.username for vote in votes if vote.choice in losers]

        # Return the winners, losers, and users who voted for each choice
        return winners, losers, winner_users, loser_users
    


       


class Comment(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name='pollcomments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    vote = models.ForeignKey(Vote, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE ,blank=True, null=True)
    def __str__(self):
        return f'{self.user.username} - {self.poll.text}'
    
  

polls/forms.py
from django import forms
from .models import Poll, Choice ,Comment



class PollAddForm(forms.ModelForm):

    choice1 = forms.CharField(label='Choice 1', max_length=100, min_length=1,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))
    choice2 = forms.CharField(label='Choice 2', max_length=100, min_length=1,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(label='Image', required=False, widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}))
    video = forms.FileField(label='Video', required=False, widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}))

    class Meta:
        model = Poll
        fields = ['text', 'choice1', 'choice2', 'image','video']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'cols': 20}),
        }


class EditPollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ['text', ]
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'cols': 20}),
            
        }


class ChoiceAddForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text' ,  ]
        widgets = {
            'choice_text': forms.TextInput(attrs={'class': 'form-control', }) ,
            
        }



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Count
from django.contrib import messages
from .models import Poll, Choice, Vote ,Comment 
from .forms import PollAddForm, EditPollForm, ChoiceAddForm ,CommentForm
from django.http import HttpResponse, JsonResponse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.urls import reverse
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import os
import redis
import json
from django.core.cache import cache
from django.views.decorators.csrf import ensure_csrf_cookie
from django.utils import timezone
from datetime import datetime
from django.views.decorators.csrf import csrf_protect
import asyncio
from asgiref.sync import sync_to_async
import json
from channels.generic.websocket import AsyncWebsocketConsumer
from polls.models import Comment
from django.utils import timezone
from datetime import datetime
from asgiref.sync import sync_to_async


from channels.generic.websocket import AsyncWebsocketConsumer
import json

from channels.generic.websocket import AsyncWebsocketConsumer
import json

from django.db.models import Count





def polls_list(request):
    all_polls = Poll.objects.all()
    search_term = ''
    if 'name' in request.GET:
        all_polls = all_polls.order_by('text')

    if 'date' in request.GET:
        all_polls = all_polls.order_by('pub_date')

    if 'vote' in request.GET:
        all_polls = all_polls.annotate(Count('vote')).order_by('vote__count')

    if 'search' in request.GET:
        search_term = request.GET['search']
        all_polls = all_polls.filter(text__icontains=search_term)

    paginator = Paginator(all_polls, 100)  # Show 6 contacts per page
    page = request.GET.get('page')
    polls = paginator.get_page(page)

    get_dict_copy = request.GET.copy()
    params = get_dict_copy.pop('page', True) and get_dict_copy.urlencode()
    print(params)
    context = {
        'polls': polls,
        'params': params,
        'search_term': search_term,
    }
    return render(request, 'polls/polls_list.html', context)


@login_required()
def list_by_user(request):
    all_polls = Poll.objects.filter(owner=request.user)
    paginator = Paginator(all_polls, 7)  # Show 7 contacts per page

    page = request.GET.get('page')
    polls = paginator.get_page(page)

    context = {
        'polls': polls,
    }
    return render(request, 'polls/polls_list.html', context)


@login_required()


def polls_add(request):
    if request.method == 'POST':
        form = PollAddForm(request.POST, request.FILES)
        if form.is_valid():
            poll = form.save(commit=False)
            poll.owner = request.user
            poll.save()

            # handle image upload for the poll
            if form.cleaned_data['image']:
                image = form.cleaned_data['image']
                # create the directory to store images if it doesn't exist
                if not os.path.exists(settings.MEDIA_ROOT):
                    os.makedirs(settings.MEDIA_ROOT)
                # save the uploaded image file to the media directory
                with open(os.path.join(settings.MEDIA_ROOT, image.name), 'wb+') as destination:
                    for chunk in image.chunks():
                        destination.write(chunk)
                # save the image url to the poll object
                poll.image = image.name

            # handle video upload for the poll
            if form.cleaned_data['video']:
                video = form.cleaned_data['video']
                # create the directory to store videos if it doesn't exist
                if not os.path.exists(settings.MEDIA_ROOT):
                    os.makedirs(settings.MEDIA_ROOT)
                # save the uploaded video file to the media directory
                with open(os.path.join(settings.MEDIA_ROOT, video.name), 'wb+') as destination:
                    for chunk in video.chunks():
                        destination.write(chunk)
                # save the video url to the poll object
                poll.video = video.name

            # create choice objects
            choice1 = Choice(poll=poll, choice_text=form.cleaned_data['choice1'])
            choice1.save()

            choice2 = Choice(poll=poll, choice_text=form.cleaned_data['choice2'])
            choice2.save()

            poll.save()

            return redirect('polls:list')
    else:
        form = PollAddForm()
    context = {
        'form': form,
    }
    return render(request, 'polls/add_poll.html', context)


@login_required
def polls_edit(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    if request.user != poll.owner:
        return redirect('home')

    if request.method == 'POST':
        form = EditPollForm(request.POST, instance=poll)
        if form.is_valid:
            form.save()
            messages.success(request, "Poll Updated successfully.",
                             extra_tags='alert alert-success alert-dismissible fade show')
            return redirect("polls:list")

    else:
        form = EditPollForm(instance=poll)

    return render(request, "polls/poll_edit.html", {'form': form, 'poll': poll})


@login_required
def polls_delete(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    poll.delete()
    messages.success(request, "Poll Deleted successfully.",
                     extra_tags='alert alert-success alert-dismissible fade show')
    return redirect("polls:list")


@login_required
def add_choice(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    if request.user != poll.owner:
        return redirect('home')

    if request.method == 'POST':
        form = ChoiceAddForm(request.POST)
        if form.is_valid:
            new_choice = form.save(commit=False)
            new_choice.poll = poll
            new_choice.save()
            messages.success(
                request, "Choice added successfully.", extra_tags='alert alert-success alert-dismissible fade show')
            return redirect('polls:edit', poll.id)
    else:
        form = ChoiceAddForm()
    context = {
        'form': form,
    }
    return render(request, 'polls/add_choice.html', context)
 

@login_required
def choice_edit(request, choice_id):
    choice = get_object_or_404(Choice, pk=choice_id)
    poll = get_object_or_404(Poll, pk=choice.poll.id)
    if request.user != poll.owner:
        return redirect('home')

    if request.method == 'POST':
        form = ChoiceAddForm(request.POST, instance=choice)
        if form.is_valid:
            new_choice = form.save(commit=False)
            new_choice.poll = poll
            new_choice.save()
            messages.success(
                request, "Choice Updated successfully.", extra_tags='alert alert-success alert-dismissible fade show')
            return redirect('polls:edit', poll.id)
    else:
        form = ChoiceAddForm(instance=choice)
    context = {
        'form': form,
        'edit_choice': True,
        'choice': choice,
    }
    return render(request, 'polls/add_choice.html', context)


@login_required
def choice_delete(request, choice_id):
    choice = get_object_or_404(Choice, pk=choice_id)
    poll = get_object_or_404(Poll, pk=choice.poll.id)
    if request.user != poll.owner:
        return redirect('home')
    choice.delete()
    messages.success(
        request, "Choice Deleted successfully.", extra_tags='alert alert-success alert-dismissible fade show')
    return redirect('polls:edit', poll.id) 



@login_required
def poll_vote(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    choice_id = request.POST.get('choice')
    comments = []
    winners, losers, winner_users, loser_users =Vote.classify_poll_results(poll_id)
    context = {
        'winners': winners,
        'losers': losers,
        'winner_users': winner_users,
        'loser_users': loser_users,
      }    
    if choice_id:
            if not poll.user_can_vote(request.user):
                messages.error(
                    request, "You already voted this poll!", extra_tags='alert alert-warning alert-dismissible fade show'
                )
            else:
                choice = Choice.objects.get(id=choice_id)
                vote = Vote(user=request.user, poll=poll, choice=choice)
                
                vote.save()
                messages.success(request, "Your vote has been recorded!", extra_tags='alert alert-success alert-dismissible fade show')
    if poll:
        comments = Comment.objects.filter(poll=poll)    
    else:
        poll = Poll(pk=poll_id)
        poll.save()
        
    return render(request, 'polls/poll_result.html', {'poll': poll, 'comments': comments , 'context':context} )
        
        


@login_required
def endpoll(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    if request.user != poll.owner:
        return render(request, 'polls/poll_result.html')


    if poll.active is True:
        poll.active = False
        poll.save()
        return render(request, 'polls/poll_result.html', {'poll': poll} )
    else:
        return render(request, 'polls/poll_result.html', {'poll': poll})
    


@login_required
def comments(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    comments = Comment.objects.filter(poll=poll)
    if request.method == 'POST':
        comment_text = request.POST.get('comment')
        if comment_text:
            comment = Comment.objects.create(
                poll=poll,
                user=request.user,
                text=comment_text,
            )
            return redirect('polls:vote', poll_id=poll_id)
    elif request.method == 'DELETE':

polls/templates/polls/add_choice.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            {% if edit_choice %}
            <h2>Update choice</h2>
            {% else %}
            <h2>Add new choice</h2>
            {% endif %}
            
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                {% if edit_choice %}
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-danger" href="{% url 'polls:choice_delete' choice.id %}" role="button" onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
                {% else %}
                <button type="submit" class="btn btn-primary">Add</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

polls/templates/polls/add_poll.html
{% extends 'base.html' %}

{% block content %}

<br>
<br>
<br>

<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <h2>Create new poll</h2>
            
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <div><button type="submit" class="btn btn-primary">Add Poll</button>
                <a  href="{% url 'polls:list' %}" role="button">Back</a></div>
               
            </form>
        </div>
    </div>
</div>
{% endblock %}

polls/templates/polls/endpoll.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="row">
        <div class="col-md-8 offset-sm-2">
            <h3 class="mt-3 mb-3 text-center">Result for: {{ poll.text }}</h3>
            <!-- progress bar -->
    <div class="progress mt-3">

        {% for choice in poll.get_result_dict %}
        <div class="progress-bar bg-{{ choice.alert_class }}" role="progressbar" style="width: {{ choice.percentage }}%;" aria-valuenow="30" aria-valuemin="0"
            aria-valuemax="100"><b>{{ choice.text }}-{{ choice.percentage|floatformat }}%</b></div>
        {% endfor %}

    </div>
            <ul class="list-group">
                {% for choice in poll.choice_set.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ choice.choice_text }}
                    <span class="badge badge-primary badge-pill">{{ choice.get_vote_count }}</span>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <a class="btn btn-primary mt-3" href="{% url 'polls:list' %}" role="button">Back To Polls</a>
        </div>
        
    </div>
</div>
{% endblock content %}

polls/templates/polls/poll_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <h2>Edit poll</h2>
            {% if messages %}
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-danger" href="{% url 'polls:delete_poll' poll.id %}" role="button" onclick="return confirm('Are you sure?')">Delete</a>
                <a class="btn btn-warning" href="{% url 'polls:add_choice' poll.id %}" role="button">Add Choice</a>
            </form>

            <div class="choices">
                <h2 class="text-center mt-3">Choices</h2>
                <hr>
                <ul class="list-group">
                    {% for choice in poll.choice_set.all %}
                    <li class="list-group-item"><a href="{% url 'polls:choice_edit' choice.id %}"><i class="fas fa-pencil-alt"></i></a>&nbsp
                        {{ choice.choice_text }}</li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
</div>
{% endblock %}

polls/templates/polls/poll_result.html
{% extends 'base.html' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>



{% load static %}

{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/papu.css' %}">
{% endblock custom_css %}
{% block content %}
<br>
<br>

<div  style="border: 0.5px #ffffff solid; width : 2000px ;height: 1px; border-bottom: none;"></div>
<div style="border: 0.5px #e9e9e9 solid;position: absolute; top: 13.6%; bottom: 0; left: 7%; width: .5px; background-color: #c5c5c5; height: 2000px;"></div>
<div style="border: 0.5px #e2e2e2 solid;position: absolute; top: 13.6%; bottom: 0; right: 1%;left: 110%; width: .5px; background-color: #c5c5c5; height: 2000px;"></div>
<div class="container" style="border: 2px #333; margin-left: 20%;" >

  <div class="row">
    <div class="col-md-8 offset-sm-2">
  
      
      <!-- progress bar -->
     <br>
      <div style="align-items: center;margin-left: 5%;margin-right: auto;">
        <h4 >{{ poll.text }}</h4>
       
        <div>
          {% if poll.image %}
          <img src="{{ poll.image.url }}" alt="{{ poll.text }}" style="height:200px; width: 200px;margin-bottom:10px;border-radius:3px;">
          {% endif %}
        </div>
        {% for choice in poll.get_result_dict %}
        {% if choice.percentage > 50 %}
        <div role="progressbar" style="margin-top:3px;width: 70%; height: 62px; position:relative;background-color: #292828;border: 0px #333 solid;padding: 0px;border-radius: 10px;">
          <div class="color-item" id="papu" role="progressbar" style="background-color: rgb(61, 168, 141);width:{{ choice.percentage }}%;border-radius: 6px; height: 60px; position:relative; ">
            <div id="result" role="progressbar">{{choice.text}}</div> 
            <div id="result" class="num" role="progressbar" data-val="{{choice.percentage|floatformat}}">1</div>
          </div>
        </div>
        {% else %}
        
        <div role="progressbar" style="margin-top:3px;width: 70%; height: 62px; position:relative;background-color: #222222;border: 0px #333 solid;padding: 0px;border-radius: 10px;">
          <div class="color-item" id="papu" role="progressbar" style="background-color: rgb(194, 10, 10);width:{{ choice.percentage }}%;border-radius: 6px; height: 60px; position:relative;">
            <div id="result" role="progressbar">{{choice.text}}</div>
            <div id="result" class="num" role="progressbar" data-val="{{choice.percentage|floatformat}}">1</div>
          </div>
        </div>
        
        {% endif %}
        {% endfor %}
         <div style="margin-left: 2%;"><h6>{{ poll.get_vote_count }} votes</h6></div>
        <br>
    <div style="margin-left:17% "> <h6>Comments:</h6></div>
    <form id="comment-form" method="POST" action="{% url 'polls:comments' poll.id %}">
      {% csrf_token %}
       <textarea class="effect-1" oninput="auto_grow(this)" id="comment-input" name="comment"  style="background-color: #252525; color: #ffffff;"></textarea>
        
      <button  id="refreshBtn" type="submit"  class="btn" style="border: #ffffff; border-radius: 13px; font-weight: 400; justify-items: center;">Send</button>
    </form>
    <div id="commentdisplay" style="position:relative;font-size: 24px; "></div>
    <div class="comments-list" style="display:flex;justify-content:center;flex-direction:column;margin-top:20px;"></div>
    
    
         {% for comment in comments.all %}
          
        
          
            <div class="comment-box" style="color:#ffffff; background-color:#000000; border:1px solid #d8d8d8; border-radius:10px; margin-bottom:10px; padding:10px; width:70%;">
            <p>{{ comment.user.username }}</p>
            <p class="comment-info" style="font-size: 15px;margin-top:0px;color:#ffffff;">{{ comment.text }}</p>
            {% if comment.user == request.user %}
              <form method="post" action="{% url 'polls:delete_comment' comment.id %}">
                {% csrf_token %}
                <button id="refreshBtn" type="submit" class="btn" style="border: #ffffff; border-radius: 13px; font-weight: 400; justify-items: center;">Delete</button>
              </form>
            {% endif %}
          </div>
          
  {% endfor %}
      <h1>{% for choice in winners %}
        <tr>
          <td>{{ choice.choice_text }}</td>
          <td>{{ choice.num_votes }}</td></h1>{{context}}
     </div>
            {% endfor %}
     <a href="{% url 'polls:list' %}" class="button" role="button"  style="bottom: 1%;">Back To Polls</a>
    
     
     
    <!-- Render comment form -->
    <script>
      const winners = [{% for choice in context.winners %}'{{ choice.choice_text }}', {% endfor %}];
      const losers = [{% for choice in context.losers %}'{{ choice.choice_text }}', {% endfor %}];
      const winner_users = [{% for user in context.winner_users %}'{{ user }}', {% endfor %}];
      const loser_users = [{% for user in context.loser_users %}'{{ user }}', {% endfor %}];
    
    
    </script>
     
  <script>
    document.getElementById('comment-form').addEventListener('submit', function(e) {
      e.preventDefault();
      const commentInputDom = document.querySelector('#comment-input');
      const comment = commentInputDom.value;
      commentSocket.send(JSON.stringify({
        'comment': comment,
      }));
      commentInputDom.value = '';
    });
  
    const pollId = {{ poll.id }};
    const commentSocket = new WebSocket(
      'ws://' + window.location.host +
      '/ws/comment/' + pollId + '/'
    );
  
    commentSocket.onmessage = function(e) {
      const data = JSON.parse(e.data);
      const commentDisplayDom = document.querySelector('#commentdisplay');
      const commentBoxDom = document.createElement('div');
      commentBoxDom.className = 'comment-box';
      commentBoxDom.style.backgroundColor = '#000000';
      commentBoxDom.style.width = '50%';
      commentBoxDom.style.border = '1px solid #d8d8d8';      
      commentBoxDom.style.borderRadius = '10px';
      commentBoxDom.style.marginBottom = '10px';
      commentBoxDom.style.padding = '10px';
      const usernameDom = document.createElement('p');
      usernameDom.innerText = data.username;
      const commentDom = document.createElement('p');
      commentDom.innerText = data.comment;
      commentDom.className = 'comment-info';
      commentDom.style.fontSize = '20px';
      commentDom.style.marginTop = '0px';
      commentDom.style.color = '#ffffff';
      commentBoxDom.appendChild(usernameDom);
      commentBoxDom.appendChild(commentDom);
      commentDisplayDom.appendChild(commentBoxDom);
    };
  </script> 
   <script>
    let valueDisplays = document.querySelectorAll(".num");
      let interval = 1200;
      valueDisplays.forEach((valueDisplay) => {
        let startValue = 0;
        let dynamicText = valueDisplay.getAttribute("data-text");
        let endValue = parseInt(valueDisplay.getAttribute("data-val"));
        let duration = Math.floor(interval / endValue);
        let counter = setInterval(function () {
          startValue += 1;
          valueDisplay.textContent =  startValue +"%";
          if (startValue >= endValue) {
            clearInterval(counter);
          }
  
        }, duration);
      });
      function auto_grow(element) {
    element.style.height = "5px";
    element.style.height = (element.scrollHeight)+"px";
        
}
      </script>
       	
<script>
  // Get the button element
  var refreshBtn = document.getElementById("refreshBtn");

  // Add event listener to the button
  refreshBtn.addEventListener("click", function() {
    // Reload the current page
    location.reload();
  });
</script>
<script>
  // Get the progress bar element
  var progressBar = document.getElementById("papu");

  // Check if the user has already seen the animation
  if (!localStorage.getItem("animationHasRun")) {
    // Add a class to the progress bar element to trigger the animation
    progressBar.classList.add("animate");

    // Store a flag in local storage to indicate that the animation has run
    localStorage.setItem("animationHasRun", true);
  }
</script>
 </div>
  </div>
</div>
</div>

</div>
<style>
  .effect-1 {
      border: none;
      border-bottom: 1px solid rgb(255, 255, 255);
      width: 60%;
      overflow: hidden;
      outline: none;
      transition: border-bottom 0.1s ease-in-out;
  }

  .effect-1:focus {
      border-bottom: 2px solid #f1ff34;
  }

 

  .effect-1:focus ~ .focus-border {
      width: 55%;
      left: 6%;
  }
</style>
 

{% endblock content %}                  
    
    
    
  
  

    
        

   
             
    





  
   

   

       